# Generated by Django 6.0.4 on 2026-05-20 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('ocupada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=255, unique=True)),
                ('necesita_certificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ci', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('intencion_agua', models.BooleanField(default=False)),
                ('intencion_servicio', models.BooleanField(default=False)),
                ('tipo_servicio_intencion', models.CharField(blank=True, max_length=50, null=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('certificado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('litros_agua', models.FloatField(default=0.0)),
                ('codigo_casa', models.ForeignKey(db_column='codigo_casa', on_delete=django.db.models.deletion.PROTECT, to='api.residencia', to_field='codigo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='comprobantes_certificados/')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='api.servicio')),
            ],
        ),
    ]
