# Generated by Django 6.0.4 on 2026-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_ESPERA', 'En Espera'), ('REVISION_PENDIENTE', 'Revisión Pendiente'), ('RECHAZADO', 'Rechazado')], default='EN_ESPERA', max_length=30),
        ),
    ]
