# Generated by Django 6.0.4 on 2026-05-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('intencion_agua', models.BooleanField(default=False)),
                ('intencion_servicio', models.BooleanField(default=False)),
                ('contrasena', models.CharField(max_length=100)),
                ('certificado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('litros_agua', models.FloatField(default=0.0)),
                ('codigo_casa', models.CharField(max_length=50)),
            ],
        ),
    ]
