# Generated by Django 6.0.4 on 2026-05-21 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuario_activo_usuario_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_PROCESO', 'En Proceso'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado'), ('CANDELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('tipo_ofrecido', models.CharField(max_length=20)),
                ('cantidad_ofrecida', models.FloatField(blank=True, null=True)),
                ('categoria_ofrecida', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_solicitado', models.CharField(max_length=20)),
                ('cantidad_solicitada', models.FloatField(blank=True, null=True)),
                ('categoria_solicitada', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
