# Generated by Django 5.2.13 on 2026-05-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_PROCESO', 'En Proceso'), ('PAUSADO', 'Pausado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20),
        ),
    ]
