# Generated by Django 6.0.4 on 2026-05-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_certificado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='comprobante',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='nombre',
            new_name='tipo_servicio',
        ),
    ]
