# Generated by Django 6.0.4 on 2026-05-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_item_remove_usuario_contrasena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('ocupada', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo_casa',
            field=models.ForeignKey(db_column='codigo_casa', on_delete=django.db.models.deletion.PROTECT, to='api.residencia', to_field='codigo'),
        ),
    ]
