# Generated by Django 6.0.4 on 2026-06-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100, unique=True)),
                ('api_conexion', models.URLField(max_length=255, unique=True)),
                ('esta_activo', models.BooleanField(default=False)),
                ('ultima_consulta', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='api_origen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='es_externo',
            field=models.BooleanField(default=False),
        ),
    ]
