# Generated by Django 6.0.4 on 2026-06-20 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_directorioservicio_servicio_api_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('leido', models.BooleanField(default=False)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_el'],
                'indexes': [models.Index(fields=['usuario', 'leido'], name='api_notific_usuario_cd4106_idx')],
            },
        ),
    ]
