# Generated by Django 6.0.6 on 2026-06-24 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_directorioservicio_servicio_api_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('transaccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='api.transaccion')),
            ],
        ),
    ]
