# Generated by Django 6.0.4 on 2026-07-04 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroComunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=255)),
                ('monto_total', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuarios_involucrados', models.IntegerField()),
                ('alicuota', models.FloatField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_comunales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
