@startuml
skinparam actorStyle stick

actor "Usuario" as user
participant "page : OfertasPage" as page
participant "api : item.api.js" as api
participant "view : OfertaView" as view
participant "orm : Oferta.objects" as orm
participant "db : PostgreSQL" as db
participant "modal : ModalDetalleOferta" as modal

activate user
user -> page : Ingresar a /ofertas
activate page

page -> api : getOfertas()
activate api

api -> view : GET /item/test/ofertas/
activate view

view -> orm : filter(estado='ACTIVO')
activate orm

orm -> db : SELECT * FROM oferta WHERE estado='ACTIVO'
activate db
db --> orm : registros físicos (Filas)
deactivate db

orm --> view : QuerySet (Objetos Python)
deactivate orm

view --> api : JSON (Texto plano)
deactivate view

api --> page : Datos de ofertas
deactivate api

page -> page : setOfertas(datos)
page --> user : Mostrar catálogo inicial

loop [Mientras el usuario modifique texto o tags]
    user -> page : handleFiltroChange(valor)
    page -> page : ofertasFiltradas = useMemo(filtrar)
    page --> user : Actualizar tarjetas visuales
end

user -> page : handleVerDetalle(oferta)
page -> modal : <<create>> instanciar(oferta)
activate modal
modal --> user : Mostrar ventana con detalles
deactivate modal

deactivate page
deactivate user
@enduml